server.memory.heap.initial_size=512m
server.memory.pagecache.size=512m
server.memory.heap.max_size=1G
server.default_listen_address=0.0.0.0

dbms.security.procedures.unrestricted=apoc.*
dbms.security.procedures.allowlist=apoc.*

# references: https://neo4j.com/docs/operations-manual/current/docker/ref-settings/
# https://neo4j.com/docs/operations-manual/current/docker/ref-settings/