name: Rust DE CI example

on: 
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-version: [stable, nightly]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
    
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock')}}

      - name: Format check
        run: cargo fmt --all -- --check 
    
      - name: Lint (Clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose